name: omikujizo-prod
services:
  app:
    build:
      context: ./app
      target: production
    privileged: true
    network_mode: host
    working_dir: /workspace
    command: python src/main2.py
    environment:
      - DISPLAY=$DISPLAY
      - PYTHONPATH=/workspace:$PYTHONPATH
